openapi: 3.0.0
info:
  title: Notification API
  version: 1.0.0
paths:
  /api/notifications:
    post:
      summary: Create a notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                message:
                  type: string
                type:
                  type: string
      responses:
        '200':
          description: Notification created
