name: Run Keploy API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  keploy-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Build & Start your app
        run: |
          npm run build || true
          npm run start &     # or npm run dev &
          sleep 5             # Give it time to boot

      - name: 📡 Download and run Keploy
        run: |
          curl -sL https://github.com/keploy/keploy/releases/latest/download/keploy-linux-amd64 -o keploy
          chmod +x keploy
          ./keploy test --path ./keploy/test-set --delay 10
