name: Keploy Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  keploy-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or your preferred version

      # 3. Install dependencies
      - name: Install NPM Dependencies
        run: npm install

      # 4. Download Keploy binary
      - name: Download Keploy CLI
        run: |
          curl -sL https://github.com/keploy/keploy/releases/latest/download/keploy-linux-amd64 -o keploy
          chmod +x keploy
          sudo mv keploy /usr/local/bin/keploy

      # 5. Start Keploy recording and your app (adjust the port and command as needed)
      - name: Run Keploy with App
        run: |
          keploy record -c "npm run start" --delay 10
