name: Keploy Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  keploy-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Download and install Keploy CLI
        run: |
          curl -s https://api.github.com/repos/keploy/keploy/releases/latest \
            | grep "browser_download_url" \
            | grep "linux-amd64" \
            | cut -d '"' -f 4 \
            | wget -i - -O keploy

          chmod +x keploy
          sudo mv keploy /usr/local/bin/keploy
          keploy version

      - name: Start Keploy recording with app
        run: |
          keploy record -c "npm run start" --delay 10
